dist: trusty
sudo: required
addons:
  apt:
    packages:
      - texinfo
env:
  - EMACS_VERSION=25.1-travis
  - EMACS_VERSION=25.3-travis
  - EMACS_VERSION=26.1-travis
  - EMACS_VERSION=26.2-travis

install:
  - curl -fsSkL https://raw.githubusercontent.com/rejeep/evm/master/go | bash
  - export PATH="$HOME/.evm/bin:$PATH"
  - evm config path /tmp
  - evm install emacs-$EMACS_VERSION
  - export PATH="/tmp/emacs-$EMACS_VERSION/bin:$PATH"

script:
  - make
